[BP] JS / Moment / Timezone lib missing when 3D mode enabled (#6603) (#247)
Related to https://github.com/geonetwork/core-geonetwork/pull/4576

Error reported
```
TypeError: Cannot read properties of undefined (reading 'guess')
```

Co-authored-by: François Prunayre <fx.prunayre@gmail.com>